# workflow name
name: MRP STORE WEB CI

# master branch on push, auto run
on: 
  push:
    branches:
      - master
      
jobs:
  build: 
    runs-on: ubuntu-18.04 
        
    steps:
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Generate web page
      run: |
        java -version
        java -jar MrpStoreWeb.jar
    
    - name: Setup Deploy Private Key 
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'gddhy' 
        git config --global user.email 'gddhywgy@gmail.com'
    - name: Deploy MRP WEB 
      run: |
        rm -f .gitignore
        cd MrpWeb
        git init
        git remote add origin git@github.com:gddhy/mrp-web.git
        bash update.sh
        